### ISSUE TITLE
Add async screenshot example

### ISSUE THREAD

**Issue by casey** [casey/glium#1]
I'd like an example which renders a scene and allows taking an async screenshot.

It should:

1. Continually render a 2D or 3D scene (doesn't matter)
2. Run at 60+ FPS
3. Write a screenshot of the scene in PNG format to disk whenever the space key is pressed.

The screenshot must be captured and written to disk asyncronously, without blocking the main thread or causing a framerate drop. Saving a screenshot must not cause the scene to be rendered more times than normally.

The example that you submit must be dedicated to the public domain using the [CC0 public domain dedication](https://creativecommons.org/publicdomain/zero/1.0/). This will make it free to use by anyone for any porpose, and is compatible with all licenses.

Ideally we can submit a PR against the main glium repo with the example, since it seems like it would be generally useful, although that isn't necessary for a solution to be accepted.

Please let me know if anything is unclear, poorly worded, or unreasonably difficult.

Thanks for reading!

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=39477822)](https://www.bountysource.com/issues/39477822-add-async-screenshot-example?utm_source=39477822&utm_medium=shield&utm_campaign=ISSUE_BADGE)

PS: Here's a repo with my synchronous screenshot capture code:

https://github.com/casey/glium-screenshot

It captures the screenshot but does not write it to disk. On my laptop I see 5-16ms per frame when running in --release mode, but a frame which takes ~40ms when a screenshot is captured. In debug mode it's much worse, 5-16ms per frame, but around 800ms when a screenshot is captured.

Ideally a solution would work in both release and debug modes, but I didn't stipulate that initially, so it's optional.

PPS: There are optimizations in tomaka/glium/master that aren't in 0.15.0, so it might be helpful to work from master on github instead of pulling from crates.io.

**Comment by casey** [comment]
Here's a repo with my synchronous screenshot capture code:

https://github.com/casey/glium-screenshot

It captures the screenshot but does not write it to disk. On my laptop I see 5-16ms per frame when running in --release mode, but a frame which takes ~120ms when a screenshot is captured. In debug mode it's even worse.

**Comment by casey** [comment]
mindtree from #rust-gamedev was super helpful in tracking down some of the sources of slowness.

Here's a performance profile of an app taking a screenshot every frame: http://imgur.com/a/igWKx

A bunch of time is wasted in calling jemalloc. Using latest glium from github fixes the time spent in allocation, although screenshotting still causes a framerate drop, so something else is still slow.

**Comment by michalsrb** [comment]
Hi, can you check if this implementation is fast enough on your machine? I don't see any noticeable framerate drop for the asynchronous screenshot when compiled in release mode.

https://github.com/michalsrb/glium-screenshot

Press [S] for synchronous screenshot, [A] for asynchronous.

Note that it's just experiment, there may be ways to simplify it or write it nicer.

**Comment by casey** [comment]
Hi there!

Trying it on my machine I'm still seeing some slowdown. On debug mode I'm seeing ~800ms frames when pressing the A key, and on release mode they're around 30ms (up from an average of 2-16ms).

I believe that although more work has been moved off of the main thread, the call to `read_raw()` still takes time, and it seems to get worse the larger the window is. Making the window small results in no delay, and making it larger makes the delay worse.

This may be an issue with the `read_as_texture2d()` call. Since it doesn't take a buffer to write into, it must be allocating a new buffer whenever a screenshot is captured, and that allocation may (somewhat surprisingly to me) be taking an excessive amount of time.

Is this the case? I wish I had profiling tools set up so that I could figure out where the delay is happening, but I don't.

**Comment by casey** [comment]
You can make the delay longer by calling read_raw() multiple times (requires making read raw take self by reference).

**Comment by michalsrb** [comment]
Most of the time is spent inside `RawImage2d::from_raw` (implementation of `Texture2dDataSource::from_raw`) which is turning a `Cow<[(u8, u8, u8, u8)>` into flat `Cow<u8>`.

It can not be moved into separate thread, because it happens inside the `PixelBuffer::read_as_texture_2d` and `PixelBuffer` is not `Send`. (I think because it can do GL calls and those must stay synchronized, but I am not sure here.)

This will be hard to optimize directly, because we can not assume the memory layout of `(u8, u8, u8, u8)`. The compiler could optimize it, but apparently it doesn't. Maybe it could be rewritten in some other way that the compiler can optimize.

Now I am curious whether glium also converts the raw memory into `(u8, u8, u8, u8)` manually or if it incorrectly assumes the tuple layout...

**Comment by casey** [comment]
Can we avoid the conversion by changing the type of the pixel buffer glium::texture::pixel_buffer::PixelBuffer<(u8, u8, u8, u8)> to another type that doesn't need to be converted?

**Comment by casey** [comment]
So, one gross hack later, it's fully async, even in debug mode.

I added the following to glium/src/texture/mod.rs:

```
impl<'a> Texture2dDataSink<(u8, u8, u8, u8)> for RawImage2d<'a, (u8, u8, u8, u8)> {
  fn from_raw(data: Cow<[(u8, u8, u8, u8)]>, width: u32, height: u32) -> Self {
    RawImage2d {
      data:   Cow::Owned(data.into_owned()),
      width:  width,
      height: height,
      format: <(u8, u8, u8, u8) as PixelValue>::get_format(),
    }
  }
}
```

And changed the signature of `read_raw()` to:

```
  fn read_raw<'a>(&self) -> glium::texture::RawImage2d<'a, (u8, u8, u8, u8)> {
    self.pixel_buffer.read_as_texture_2d().unwrap()
  }
```

Which returns the vector of tuples directly instead of needing to convert/reallocate in the main thread.

It can then be converted to a flat vector in save_to_file, which runs off the main thread, and so everything is fully async.

I'll probably open a PR on glium to propose that these versions of read_raw be added to glium, so that in cases where the conversion is unacceptably slow it can be moved to a different thread.

So, case closed!

To get the bounty, I think you need to claim it on [bountysource.com](https://www.bountysource.com/issues/39477822-add-async-screenshot-example).

Also, can you confirm that you dedicate your implementation to the public domain with the cc0 public domain dedication?

Thanks so much for your help!

**Comment by michalsrb** [comment]
I've updated my fork of your glium-screenshot to use it's own struct that implements `Texture2dDataSink` to prevent the `(u8, u8, u8, u8)` -> u8 conversion in main thread.

> To get the bounty, I think you need to claim it on bountysource.com.

Will do, thanks.

> Also, can you confirm that you dedicate your implementation to the public domain with the cc0 public domain dedication?

Sure, I do. I'll clean up and comment more the code and try to submit it as glium example.

**Comment by casey** [comment]
Perfect, you're awesome :–)
